package Genealogy.URLConnexion.Geneanet;

import org.junit.jupiter.api.Test;

import static Genealogy.URLConnexion.Geneanet.GeneanetBrowser.testSearch;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class GeneanetBrowserTest {

    public GeneanetBrowserTest() {

    }

    public static String readPerson(String url) {
        return testSearch(url).toString();
    }

    @Test
    public void integrationTest() {
        assertEquals("GeneanetPerson{url='https://gw.geneanet.org/dil?lang=fr&p=jacques&n=de+silliers', geneanetURL='https://gw.geneanet.org/dil?lang=fr&iz=21086&m=RL&i1=10147&i2=21086&b1=1&b2=6120', firstName='Jacques', familyName='de SILLIERS', gender='M', placeOfBirth='Les Sièges', placeOfDeath='Saint-Hilaire', father='https://gw.geneanet.org/dil?lang=fr&p=jacques&n=de+silliers&oc=1', mother='https://gw.geneanet.org/dil?lang=fr&p=francoise&n=de+chicault', siblings='https://gw.geneanet.org/dil?lang=fr&p=charles&n=de+silliers', children='https://gw.geneanet.org/dil?lang=fr&p=suzanne+jeanne&n=de+silliers;https://gw.geneanet.org/dil?lang=fr&p=jacques&n=de+silliers&oc=2;https://gw.geneanet.org/dil?lang=fr&p=charles&n=de+silliers&oc=1;https://gw.geneanet.org/dil?lang=fr&p=charlotte+catherine&n=de+silliers;https://gw.geneanet.org/dil?lang=fr&p=jeanne+claude&n=de+silliers;https://gw.geneanet.org/dil?lang=fr&p=jean&n=de+silliers', marriage='https://gw.geneanet.org/dil?lang=fr&p=marguerite&n=charpentier;{null=null}https://gw.geneanet.org/dil?lang=fr&p=madeleine&n=de+pollangis;{09/02/1672=Saint-Hilaire - Sens}', searched='true'", readPerson("https://gw.geneanet.org/dil?lang=fr&p=jacques&n=de+silliers"));
        assertEquals("GeneanetPerson{url='https://gw.geneanet.org/dil?lang=fr&p=jacques&n=de+silliers&oc=1', geneanetURL='https://gw.geneanet.org/dil?lang=fr&iz=21086&m=RL&i1=10426&i2=21086&b1=1&b2=12240', firstName='Jacques', familyName='de SILLIERS', gender='M', placeOfDeath='Les Sièges', children='https://gw.geneanet.org/dil?lang=fr&p=charles&n=de+silliers;https://gw.geneanet.org/dil?lang=fr&p=jacques&n=de+silliers', marriage='https://gw.geneanet.org/dil?lang=fr&p=francoise&n=de+chicault;{1644=null}', searched='true'", readPerson("https://gw.geneanet.org/dil?lang=fr&p=jacques&n=de+silliers&oc=1"));
        assertEquals("GeneanetPerson{url='https://gw.geneanet.org/dil?lang=fr&p=marie&n=fremy', geneanetURL='https://gw.geneanet.org/dil?lang=fr&iz=21086&m=RL&i1=672&i2=21086&b1=1&b2=373', firstName='Marie', familyName='FREMY', gender='F', birthDate='11/01/1716', placeOfBirth='Tannerre-en-Puisaye', deathDate='11/09/1763', placeOfDeath='La Ferté-Loupière', father='https://gw.geneanet.org/dil?lang=fr&p=claude&n=fremy', mother='https://gw.geneanet.org/dil?lang=fr&p=marie&n=digue', children='https://gw.geneanet.org/dil?lang=fr&p=theodule&n=courty;https://gw.geneanet.org/dil?lang=fr&p=andre&n=courty;https://gw.geneanet.org/dil?lang=fr&p=simon&n=courty;https://gw.geneanet.org/dil?lang=fr&p=marie&n=courty&oc=1;https://gw.geneanet.org/dil?lang=fr&p=pierre&n=courty&oc=3', marriage='https://gw.geneanet.org/dil?lang=fr&p=pierre&n=courty;{02/07/1743=Villiers-Saint-Benoît}', searched='true'", readPerson("https://gw.geneanet.org/dil?lang=fr&p=marie&n=fremy"));
        assertEquals("GeneanetPerson{url='https://gw.geneanet.org/dil?lang=fr&p=edme+aime&n=archambault', geneanetURL='https://gw.geneanet.org/dil?lang=fr&iz=21086&m=RL&i1=3607&i2=21086&b1=1&b2=2996', firstName='Edme (Aimé)', familyName='ARCHAMBAULT', gender='M', placeOfBirth='Aillant-sur-Tholon', placeOfDeath='Aillant-sur-Milleron', father='https://gw.geneanet.org/dil?lang=fr&p=aime&n=archambault', mother='https://gw.geneanet.org/dil?lang=fr&p=guillemette&n=rondin', children='https://gw.geneanet.org/dil?lang=fr&p=nicolas&n=archambault', marriage='https://gw.geneanet.org/dil?lang=fr&p=francoise&n=nian;{10/06/1670=La Bussière}', searched='true'", readPerson("https://gw.geneanet.org/dil?lang=fr&p=edme+aime&n=archambault"));
        assertEquals("GeneanetPerson{url='https://gw.geneanet.org/dil?lang=fr&p=aubin+gustave&n=ledroit', firstName='Aubin, \"Gustave\"', familyName='LEDROIT', gender='M', birthDate='01/03/1861', placeOfBirth='Les Benoîts', deathDate='1933', burialDate='1933', placeOfBurial='Dammarie-sur-Loing', father='https://gw.geneanet.org/dil?lang=fr&p=jean+baptiste&n=ledroit', mother='https://gw.geneanet.org/dil?lang=fr&p=rosalie+anastasie&n=fournerat', siblings='https://gw.geneanet.org/dil?lang=fr&p=camille+anastase&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=rosalie+anastasie&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=francois&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=marie+rosalie&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=firmin+alexandre&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=adrien&n=ledroit', children='https://gw.geneanet.org/dil?lang=fr&p=therese+honorine&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=zelie+marguerite&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=alice+eugenie&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=eugene+gustave&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=lucie+marie&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=juliette+julia&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=georges+lucien&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=charles+maurice&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=maurice+emile&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=marcel+desire&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=rene+henri&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=sans+nom&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=sans+nom&n=ledroit&oc=1;https://gw.geneanet.org/dil?lang=fr&p=germaine+georgette&n=ledroit;https://gw.geneanet.org/dil?lang=fr&p=madeleine+henriette&n=ledroit', marriage='https://gw.geneanet.org/dil?lang=fr&p=leontine+victorine&n=archambault;{27/01/1912=Saint-Maurice-sur-Aveyron}https://gw.geneanet.org/dil?lang=fr&p=victorine&n=berton;{30/10/1883=Maison commune - Saint-Maurice-sur-Aveyron}', image='https://gw.geneanet.org/public/img/media/deposits/3a/f1/25374671/medium.jpg?t=1603832923', searched='true'", testSearch("https://gw.geneanet.org/dil?lang=fr&iz=21086&p=aubin+gustave&n=ledroit").toString());
        assertEquals("GeneanetPerson{url='https://gw.geneanet.org/dil?lang=fr&p=leontine+victorine&n=archambault', firstName='Léontine, Victorine', familyName='ARCHAMBAULT', gender='F', birthDate='24/02/1855', placeOfBirth='Assigny', children='https://gw.geneanet.org/dil?lang=fr&p=louis+alexandre&n=aligon;https://gw.geneanet.org/dil?lang=fr&p=armantine+marie&n=aligon;https://gw.geneanet.org/dil?lang=fr&p=augustin+henri&n=aligon;https://gw.geneanet.org/dil?lang=fr&p=lucie+juliette&n=aligon;https://gw.geneanet.org/dil?lang=fr&p=marie+marguerite&n=aligon;https://gw.geneanet.org/dil?lang=fr&p=victoire+josephine&n=aligon;https://gw.geneanet.org/dil?lang=fr&p=amede+armand&n=aligon', marriage='https://gw.geneanet.org/dil?lang=fr&p=alexandre+joseph&n=aligon;{13/01/1874=Beaulieu-sur-Loire}https://gw.geneanet.org/dil?lang=fr&p=auguste&n=gessat;{25/01/1901=Rogny-les-Sept-Écluses}https://gw.geneanet.org/dil?lang=fr&p=aubin+gustave&n=ledroit;{27/01/1912=Saint-Maurice-sur-Aveyron}', searched='true'", testSearch("https://gw.geneanet.org/dil?lang=fr&p=leontine+victorine&n=archambault").toString());
        //assertEquals("", readPerson(""));
    }

}